Repository wecode-bootcamp-korea/14-1st-Gotchapedia-frontend, pull requests merged in 2020-11, with the labels that each got.

#1 [고은정] Add: Nav바 UI 완성, 로그인 회원가입 모달창 구현
  package-lock.json
  package.json
  public/images/googleBtn.png
  public/images/kakaoBtn.png
  public/images/netflix.png
  public/images/poster1.jpg
  public/images/profile.jpg
  public/images/watchaSmall.png
  public/images/watchaText.png
  public/images/watchapediaTextCol.png
  public/index.html
  src/Routes.js
  src/components/Nav/Login/Login.js
  src/components/Nav/Login/login.scss
  src/components/Nav/Nav.js
  src/components/Nav/Signin/Signin.js
  src/components/Nav/Signin/signin.scss
  src/components/Nav/Signup/Signup.js
  src/components/Nav/Signup/signup.scss
  src/components/Nav/nav.scss
  src/pages/Mypage/Mytaste/Mytaste.js
  src/pages/Mypage/Mytaste/mytaste.scss
  src/styles/common.scss
Labels: Status: Accepted

#2 [김태현] Add: 영화 상세페이지 UI 구현완료
  package-lock.json
  package.json
  public/Data/contentdata.json
  public/images/brianShelby.webp
  public/images/cameronCrow.jpg
  public/images/cameronDiaz.jpeg
  public/images/chorong2.png
  public/images/headerImage.jpg
  public/images/kurtRussel.jpg
  public/images/penelopeCruise.jpeg
  public/images/tomcruise.jpeg
  public/images/vanilaSkyHeader.png
  public/images/vanilaSkyPoster.jpeg
  public/images/vaniliaSkyImage.png
  public/index.html
  src/Routes.js
  src/components/Nav/Signup/Signup.js
  src/pages/MovieDetail/MovieContent/CastingList/CastingList.js
  src/pages/MovieDetail/MovieContent/CastingList/castingList.scss
  src/pages/MovieDetail/MovieContent/CommentBox/CommentBox.js
  src/pages/MovieDetail/MovieContent/CommentBox/CommentBox.scss
  src/pages/MovieDetail/MovieContent/CommentBox/CommnetDetail/CommentDetail.js
  src/pages/MovieDetail/MovieContent/CommentBox/CommnetDetail/CommentDetail.scss
  src/pages/MovieDetail/MovieContent/CommentWrite/CommentWrite.js
  src/pages/MovieDetail/MovieContent/CommentWrite/CommentWrite.scss
  src/pages/MovieDetail/MovieContent/MovieContent.js
  src/pages/MovieDetail/MovieContent/Overview/Overview.js
  src/pages/MovieDetail/MovieContent/Overview/overview.scss
  src/pages/MovieDetail/MovieContent/movieContent.scss
  src/pages/MovieDetail/MovieDetail.js
  src/pages/MovieDetail/MovieHeader/MovieHeader.js
  src/pages/MovieDetail/MovieHeader/StarRating/StarRating.js
  src/pages/MovieDetail/MovieHeader/StarRating/StarRating.scss
  src/pages/MovieDetail/MovieHeader/WantToSee/WantToSee.js
  src/pages/MovieDetail/MovieHeader/WantToSee/wantToSee.scss
  src/pages/MovieDetail/MovieHeader/movieHeader.scss
  src/pages/MovieDetail/MovieSide/GalleryBox/GalleryBox.js
  src/pages/MovieDetail/MovieSide/GalleryBox/galleryBox.scss
  src/pages/MovieDetail/MovieSide/MovieSide.js
  src/pages/MovieDetail/MovieSide/VideoBox/VideoBox.js
  src/pages/MovieDetail/MovieSide/VideoBox/videoBox.scss
  src/pages/MovieDetail/MovieSide/movieSide.scss
  src/pages/MovieDetail/movieDetail.scss
  src/styles/common.scss
Labels: Status: 리뷰 요청

#3 [김병준] Add: ThemeBox 진행중
  package-lock.json
  package.json
  public/Data/movielist.json
  public/images/hangover.jpg
  public/images/totheleft.jpeg
  public/images/totheright.jpeg
  src/Routes.js
  src/components/Footer/Footer.js
  src/components/Footer/footer.scss
  src/components/Nav/Login/Login.js
  src/components/Nav/Login/login.scss
  src/components/Nav/Nav.js
  src/components/Nav/Signup/Signup.js
  src/pages/Main/ThemeBox/MovieBox/MovieBox.js
  src/pages/Main/ThemeBox/MovieBox/movieBox.scss
  src/pages/Main/ThemeBox/ThemeBox.js
  src/pages/Main/ThemeBox/themeBox.scss
Labels: Status: Accepted

#6 [김병준] Add: 로그인&회원가입 기능 구현중
  public/Data/movielist.json
  src/components/Nav/Nav.js
  src/components/Nav/Signup/Signup.js
  src/components/Nav/Signup/signup.scss
  src/config.js
  src/pages/Main/Main.js
  src/pages/Main/ThemeBox/MovieBox/MovieBox.js
  src/pages/Main/ThemeBox/MovieBox/movieBox.scss
  src/pages/Main/ThemeBox/ThemeBox.js
  src/pages/Main/ThemeBox/themeBox.scss
Labels: Status: 추가 기능 구현중

#5 [김태현] Add: 영화 상세페이지 댓글 기능 구현
  package-lock.json
  package.json
  public/Data/contentdata.json
  public/images/akiraHeaderImage.jpg
  public/images/mainImage.jpeg
  public/images/starhalf.png
  public/images/starhalf2.png
  public/images/url1.jpg
  public/images/url2.png
  public/images/url3.png
  src/config.js
  src/pages/Main/ThemeBox/MovieBox/MovieBox.js
  src/pages/Main/ThemeBox/ThemeBox.js
  src/pages/MovieDetail/MovieContent/CastingList/CastingList.js
  src/pages/MovieDetail/MovieContent/CastingList/castingList.scss
  src/pages/MovieDetail/MovieContent/CommentBox/AddComment/AddComment.js
  src/pages/MovieDetail/MovieContent/CommentBox/AddComment/AddComment.scss
  src/pages/MovieDetail/MovieContent/CommentBox/CommentBox.js
  src/pages/MovieDetail/MovieContent/CommentBox/CommentBox.scss
  src/pages/MovieDetail/MovieContent/CommentBox/CommnetDetail/CommentDetail.js
  src/pages/MovieDetail/MovieContent/CommentBox/CommnetDetail/CommentDetail.scss
  src/pages/MovieDetail/MovieContent/CommentBox/CommnetDetail/CommentDetailBox/CommentDetailBox.js
  src/pages/MovieDetail/MovieContent/CommentBox/CommnetDetail/CommentDetailBox/CommentDetailBox.scss
  src/pages/MovieDetail/MovieContent/CommentWrite/CommentWrite.js
  src/pages/MovieDetail/MovieContent/CommentWrite/CommentWrite.scss
  src/pages/MovieDetail/MovieContent/MovieContent.js
  src/pages/MovieDetail/MovieContent/Overview/Overview.js
  src/pages/MovieDetail/MovieContent/Overview/overview.scss
  src/pages/MovieDetail/MovieContent/ShowComment/ShowComment.js
  src/pages/MovieDetail/MovieContent/ShowComment/showComment.scss
  src/pages/MovieDetail/MovieContent/movieContent.scss
  src/pages/MovieDetail/MovieDetail.js
  src/pages/MovieDetail/MovieHeader/MovieHeader.js
  src/pages/MovieDetail/MovieHeader/StarRating/StarRating.js
  src/pages/MovieDetail/MovieHeader/StarRating/StarRating.scss
  src/pages/MovieDetail/MovieHeader/WantToSee/WantToSee.js
  src/pages/MovieDetail/MovieHeader/WantToSee/wantToSee.scss
  src/pages/MovieDetail/MovieHeader/movieHeader.scss
  src/pages/MovieDetail/MovieSide/GalleryBox/GalleryBox.js
  src/pages/MovieDetail/MovieSide/GalleryBox/galleryBox.scss
  src/pages/MovieDetail/MovieSide/MovieSide.js
  src/pages/MovieDetail/MovieSide/VideoBox/VideoBox.js
  src/pages/MovieDetail/MovieSide/VideoBox/videoBox.scss
Labels: Status: 리뷰 요청

#7 [김태현] Add: Main UI 수정 및 댓글 삭제기능 추가
  public/Data/movielist.json
  public/images/aprilstory.jpeg
  public/images/beforeIdisappear.jpg
  public/images/bladerunner.jpg
  public/images/harry&sally.jpg
  public/images/matrix.jpg
  public/images/millenniummambo.jpg
  public/images/mononokehime.jpg
  public/images/vampire.jpeg
  src/components/Footer/Footer.js
  src/components/Footer/footer.scss
  src/config.js
  src/pages/Main/ThemeBox/MovieBox/MovieBox.js
  src/pages/Main/ThemeBox/MovieBox/movieBox.scss
  src/pages/Main/ThemeBox/ThemeBox.js
  src/pages/Main/ThemeBox/themeBox.scss
  src/pages/MovieDetail/MovieContent/CommentBox/CommentBox.js
  src/pages/MovieDetail/MovieContent/MovieContent.js
  src/pages/MovieDetail/MovieContent/ShowComment/ShowComment.js
  src/pages/MovieDetail/MovieContent/ShowComment/showComment.scss
  src/pages/MovieDetail/MovieDetail.js
Labels: Status: 리뷰 요청

#4 [고은정] Add: My Taste 취향 분석 컴포넌트 전체적 UI 완료 및 기능 구현
  .gitignore
  package-lock.json
  package.json
  public/Data/myPage.json
  public/Data/my_star.json
  public/Data/preferredCountryGenre.json
  public/images/belovedActor.png
  public/images/gotchapedia.png
  public/images/gotchapediaPink.png
  public/images/gotchapediaSmall.png
  public/images/gotchapediaText.png
  public/images/gotchapediaTextCol.png
  public/images/gotchapediaTextCol1.png
  public/images/gotchapediawhite.png
  public/images/graph.png
  public/images/logoPink.png
  public/images/movieTag.png
  public/index.html
  src/Routes.js
  src/components/Nav/Nav.js
  src/components/Nav/Search/Search.js
  src/components/Nav/Search/search.scss
  src/components/Nav/nav.scss
  src/config.js
  src/index.js
  src/pages/MovieDetail/MovieSide/GalleryBox/galleryBox.scss
  src/pages/MovieDetail/MovieSide/MovieClip/MovieClip.js
  src/pages/MovieDetail/MovieSide/MovieClip/movieClip 2.scss
  src/pages/MovieDetail/MovieSide/MovieClip/movieClip.scss
  src/pages/MovieDetail/movieDetail.scss
  src/pages/Mypage/Mypage.js
  src/pages/Mypage/Mytaste/Chart/Chart.js
  src/pages/Mypage/Mytaste/Mytaste.js
  src/pages/Mypage/Mytaste/PreferredCountreNation/PreferredCountryGenre.js
  src/pages/Mypage/Mytaste/mytaste.scss
  src/pages/Mypage/Mytaste/wordCloud/wordCloud.js
  src/pages/Mypage/mypage.scss
  src/styles/common.scss
Labels: Status: 리뷰 요청

#8 [김병준]Add: themebox 슬라이드 기능 추가
  package-lock.json
  package.json
  src/components/Nav/Nav.js
  src/components/Nav/Signup/Signup.js
  src/pages/Main/ThemeBox/ThemeBox.js
  src/pages/MovieDetail/MovieSide/GalleryBox/galleryBox.scss
Labels: Status: 리뷰 요청

#9 [김태현] movie main page -> movie detail data 동적 라우팅 작업 중
  public/Data/movielist.json
  src/Routes.js
  src/config.js
  src/pages/Main/Main.js
  src/pages/Main/ThemeBox/MovieBox/MovieBox.js
  src/pages/Main/ThemeBox/ThemeBox.js
  src/pages/MovieDetail/MovieContent/CommentBox/AddComment/AddComment.js
  src/pages/MovieDetail/MovieContent/CommentBox/CommentBox.js
  src/pages/MovieDetail/MovieContent/CommentBox/CommnetDetail/CommentDetail.js
  src/pages/MovieDetail/MovieContent/CommentBox/CommnetDetail/CommentDetailBox/CommentDetailBox.js
  src/pages/MovieDetail/MovieContent/MovieContent.js
  src/pages/MovieDetail/MovieContent/Overview/Overview.js
  src/pages/MovieDetail/MovieContent/ShowComment/ShowComment.js
  src/pages/MovieDetail/MovieContent/ShowComment/showComment.scss
  src/pages/MovieDetail/MovieDetail.js
  src/pages/MovieDetail/MovieHeader/MovieHeader.js
  src/pages/MovieDetail/MovieSide/MovieClip/MovieClip.js
  src/pages/MovieDetail/MovieSide/MovieSide.js
Labels: Status: 리뷰 요청

#10 [고은정] 마이페이지 이미지 저장 기능 구현 및 리팩토링
  README.md
  public/Data/belovedDirector.json
  public/Data/belovedPeople.json
  public/Data/contentdata.json
  public/Data/mainpage.json
  public/Data/my_star.json
  public/Data/response.json
  public/images/defaultProfile.png
  src/Routes.js
  src/components/Nav/Nav.js
  src/components/Nav/Search/Search.js
  src/components/Nav/Search/search.scss
  src/components/Nav/Signup/Signup.js
  src/components/Nav/Signup/signup.scss
  src/components/Nav/nav.scss
  src/config.js
  src/pages/Main/Main.js
  src/pages/Main/ThemeBox/ThemeBox.js
  src/pages/MovieDetail/MovieContent/Overview/Overview.js
  src/pages/MovieDetail/MovieDetail.js
  src/pages/MovieDetail/MovieSide/GalleryBox/GalleryBox.js
  src/pages/MovieDetail/MovieSide/MovieClip/movieClip 2.scss
  src/pages/MovieDetail/MovieSide/MovieClip/movieClip.scss
  src/pages/MovieDetail/MovieSide/MovieSide.js
  src/pages/MovieDetail/MovieSide/VideoBox/VideoBox.js
  src/pages/MovieDetail/MovieSide/VideoBox/videoBox.scss
  src/pages/Mypage/Mypage.js
  src/pages/Mypage/Mytaste/BelovedPeople/BelovedPeople.js
  src/pages/Mypage/Mytaste/BelovedPeople/belovedPeople.scss
  src/pages/Mypage/Mytaste/Chart/Chart.js
  src/pages/Mypage/Mytaste/ImgInput/ImgInput.js
  src/pages/Mypage/Mytaste/ImgInput/imgInput.scss
  src/pages/Mypage/Mytaste/Mytaste.js
  src/pages/Mypage/Mytaste/PreferredCountreNation/PreferredCountryGenre.js
  src/pages/Mypage/Mytaste/mytaste.scss
  src/service/image_uploader.js
  src/styles/common.scss
Labels: Status: 리뷰 요청

#12 [김병준] Add 회원가입 및 로그인 기능 추가
  public/Data/movielist.json
  src/components/Nav/Signup/Signup.js
  src/components/Nav/Signup/signup.scss
  src/pages/Main/Main.js
  src/pages/Main/ThemeBox/ThemeBox.js
  src/pages/Main/ThemeBox/themeBox.scss
Labels: Status: 수정 요청, Status: 컨플릭트 해결 요청

#13 [김태현] 무비디테일 페이지 댓글 CRUD 및 댓글 백엔드 연결중
  src/Routes.js
  src/components/Nav/Login/Login.js
  src/components/Nav/Login/login.scss
  src/config.js
  src/pages/MovieDetail/MovieContent/CommentBox/AddComment/AddComment.scss
  src/pages/MovieDetail/MovieContent/CommentBox/CommentBox.js
  src/pages/MovieDetail/MovieContent/CommentBox/CommnetDetail/CommentDetail.js
  src/pages/MovieDetail/MovieContent/CommentBox/CommnetDetail/CommentDetailBox/CommentDetailBox.js
  src/pages/MovieDetail/MovieContent/CommentBox/CommnetDetail/CommentDetailBox/CommentDetailBox.scss
  src/pages/MovieDetail/MovieContent/CommentWrite/CommentWrite.scss
  src/pages/MovieDetail/MovieContent/MovieContent.js
  src/pages/MovieDetail/MovieContent/Overview/Overview.js
  src/pages/MovieDetail/MovieContent/ShowComment/ShowComment.js
  src/pages/MovieDetail/MovieContent/movieContent.scss
  src/pages/MovieDetail/MovieHeader/HoverRating/HoverRating.js
  src/pages/MovieDetail/MovieHeader/HoverRating/hoverRating.scss
  src/pages/MovieDetail/MovieHeader/MovieHeader.js
  src/pages/MovieDetail/MovieHeader/StarRating/StarRating.js
  src/pages/MovieDetail/MovieHeader/WantToSee/WantToSee.js
  src/pages/MovieDetail/MovieHeader/WantToSee/wantToSee.scss
  src/pages/MovieDetail/MovieSide/GalleryBox/GalleryBox.js
  src/pages/Mypage/mypage.scss
Labels: 리뷰 진행 중

#16 [김병준] 회원가입 및 로그인 UI 수정 최종본
  public/images/chatlogo.png
  public/images/googlelogo.jpg
  public/images/googlelogo.png
  public/images/kakaologo.png
  src/components/Nav/Nav.js
  src/components/Nav/Search/Search.js
  src/components/Nav/Signup/Signup.js
  src/components/Nav/Signup/signup.scss
  src/pages/Main/ThemeBox/ThemeBox.js
Labels: 리뷰 진행 중

#17 [Fix] 서버 통신 기능구현 중
  src/Routes.js
  src/components/Nav/Search/Search.js
  src/config.js
  src/pages/Main/Main.js
  src/pages/Main/ThemeBox/MovieBox/MovieBox.js
  src/pages/MovieDetail/MovieContent/CommentBox/CommnetDetail/CommentDetail.js
  src/pages/MovieDetail/MovieContent/MovieContent.js
  src/pages/MovieDetail/MovieContent/Overview/Overview.js
  src/pages/MovieDetail/MovieDetail.js
  src/pages/MovieDetail/MovieHeader/HoverRating/HoverRating.js
  src/pages/MovieDetail/MovieHeader/MovieHeader.js
  src/pages/MovieDetail/MovieHeader/movieHeader.scss
  src/pages/Mypage/Mytaste/ImgInput/imgInput.scss
Labels: Status: 리뷰 요청

#18 [Fix] 별점 기능 수정중
  src/config.js
  src/pages/Main/ThemeBox/ThemeBox.js
  src/pages/MovieDetail/MovieContent/MovieContent.js
  src/pages/MovieDetail/MovieContent/Overview/Overview.js
  src/pages/MovieDetail/MovieDetail.js
  src/pages/MovieDetail/MovieHeader/HoverRating/HoverRating.js
  src/pages/MovieDetail/MovieHeader/MovieHeader.js
  src/pages/MovieDetail/MovieSide/MovieSide.js
Labels: Status: 리뷰 요청

#19 [Set] 머지 위해 임시 커밋
  public/Data/belovedDirector.json
  src/Routes.js
  src/components/Nav/Search/Search.js
  src/config.js
  src/pages/Main/Main.js
  src/pages/Main/main.scss
  src/pages/MovieDetail/MovieContent/CommentBox/CommentBox.js
  src/pages/MovieDetail/MovieContent/CommentBox/CommnetDetail/CommentDetail.js
  src/pages/MovieDetail/MovieContent/CommentBox/CommnetDetail/CommentDetailBox/CommentDetailBox.js
  src/pages/MovieDetail/MovieContent/CommentWrite/CommentWrite.scss
  src/pages/MovieDetail/MovieContent/MovieContent.js
  src/pages/MovieDetail/MovieDetail.js
  src/pages/MovieDetail/MovieHeader/HoverRating/HoverRating.js
  src/pages/MovieDetail/MovieHeader/MovieHeader.js
  src/pages/MovieDetail/MovieSide/MovieSide.js
  src/pages/Mypage/Mytaste/BelovedPeople/BelovedDirector.js
  src/pages/Mypage/Mytaste/Mytaste.js
Labels: Status: Accepted

#22 [Add] my taste 기능 추가 및 UI 수정 작업
  public/Data/mainpage.json
  src/components/Nav/Nav.js
  src/components/Nav/Search/Search.js
  src/components/Nav/Signup/Signup.js
  src/config.js
  src/pages/Main/Main.js
  src/pages/Main/ThemeBox/ThemeBox.js
  src/pages/Main/main.scss
  src/pages/Mypage/Mytaste/PreferredCountreNation/PreferredCountryGenre.js
Labels: Status: 추가 기능 구현중

#21 [김태현] 무비 상세페이지 댓글 삭제작업 진행중
  src/config.js
  src/pages/MovieDetail/MovieContent/CommentBox/CommentBox.js
  src/pages/MovieDetail/MovieContent/CommentBox/CommentBox.scss
  src/pages/MovieDetail/MovieContent/CommentBox/CommnetDetail/CommentDetail.js
  src/pages/MovieDetail/MovieContent/MovieContent.js
  src/pages/MovieDetail/MovieContent/Overview/Overview.js
  src/pages/MovieDetail/MovieContent/ShowComment/ShowComment.js
  src/pages/MovieDetail/MovieDetail.js
  src/pages/MovieDetail/MovieHeader/HoverRating/HoverRating.js
  src/pages/MovieDetail/MovieHeader/MovieHeader.js
  src/pages/MovieDetail/MovieSide/MovieSide.js
Labels: Status: 도움 요청, Status: 리뷰 요청

#23 [Refactor] 최종 UI 수정 및 기능 오류 해결
  public/images/vanila.jpg
  src/components/Nav/Search/Search.js
  src/components/Nav/Signup/Signup.js
  src/components/Nav/Signup/signup.scss
  src/config.js
  src/pages/Main/Main.js
  src/pages/Main/main.scss
  src/pages/MovieDetail/MovieContent/MovieContent.js
  src/pages/MovieDetail/MovieSide/MovieSide.js
  src/pages/Mypage/Mytaste/BelovedPeople/BelovedDirector.js
  src/pages/Mypage/Mytaste/Mytaste.js
Labels: Status: Accepted
